# Generated by Django 3.1.1 on 2020-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
